"""private messages

Revision ID: 005c51fba223
Revises: 7b790433a107
Create Date: 2024-03-20 11:48:52.490743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005c51fba223'
down_revision = '7b790433a107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_message_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_sender_id'), ['sender_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_message_read_time')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_message_recipient_id'))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
